### ISSUE TITLE
Add Carthage to snapshot

### ISSUE THREAD

**Issue by nhducit** [infinitered/solidarity-react-native#16]

**Comment by GantMan** [comment]
Interested in taking a shot at a PR?

**Comment by nhducit** [comment]
@GantMan sure, I'm going to release my company application for the first time. Will do PR when I have time

**Comment by GantMan** [comment]
Excellent!  Let me know if you need any help.

**Comment by GantMan** [comment]
@nhducit - I'm unfamiliar with carthage, is that a CLI I can detect with which?   Do you want to elaborate the detection needed, and we can psuedocode in this ticket?
