### ISSUE TITLE
Wrong React Native version found

### ISSUE THREAD

**Issue by TheAlmightyBob** [infinitered/solidarity-react-native#19]
It seems that Solidarity-React-Native expects to run `react-native` from `/usr/local/bin/react-native`, which would output something like:
```
react-native-cli: 2.0.1
react-native: 0.52.2
```
But instead it is executing `react-native` from the project's `node_modules/.bin/react-native`, which outputs the version in this format:
```
Loading /<project>/rn-cli.config.js
Scanning folders for symlinks in /<project>/node_modules (41ms)
0.52.2
```

Thus it will, in this example, report the version as "41" (and report a different version each time solidarity is run).

All but one person on my team is seeing this behavior (and that person just gets "0.0.0," so still wrong, just a different wrong... no idea what's happening there yet).

**Comment by TheAlmightyBob** [comment]
@skellock filed a more detailed and active version of this bug over at https://github.com/infinitered/solidarity/issues/175, so I'll close this one.

**Comment by GantMan** [comment]
This has been fixed.  Just shoring up a few things with the upstream and then probably going to cut version 2.0 & :shipit:
